// FETCH POKEDEX
export const FETCH_POKEDEX = 'FETCH_POKEDEX'

//FETCH POKE DETAIL
export const FETCH_POKE_DETAIL = 'FETCH_POKE_DETAIL'
export const FETCH_POKE_PENDING = 'FETCH_POKE_PENDING'
export const FETCH_POKE_ERROR = 'FETCH_POKE_ERROR'

//FETCH RANDOM LOADING IMAGE
export const LOADING_IMAGE = 'LOADING_IMAGE'